/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  cacheDirectory: "./node_modules/.cache/remix",
  ignoredRouteFiles: [".*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],
  serverDependenciesToBundle: [
    "@mdx-js/esbuild",
    "bail",
    "ccount",
    "character-entities-html4",
    "character-entities-legacy",
    "character-entities",
    "character-reference-invalid",
    "comma-separated-tokens",
    "decode-named-character-reference",
    "fault",
    "is-alphabetical",
    "is-alphanumerical",
    "is-decimal",
    "is-hexadecimal",
    "is-reference",
    "markdown-table",
    "marked",
    "parse-entities",
    "periscopic",
    "property-information",
    "rehype-autolink-headings",
    "rehype-code-titles",
    "rehype-parse",
    "rehype-prism-plus",
    "rehype-slug",
    "rehype-toc",
    "remark-directive",
    "remark-frontmatter",
    "remark-gfm",
    "remark-mdx",
    "remark-parse",
    "remark-rehype",
    "space-separated-tokens",
    "stringify-entities",
    "trough",
    "unified",
    "web-namespaces",
    "zwitch",
    /vfile-.*/,
    /^@mdx-js\/mdx.*/,
    /^estree-util-.*/,
    /^refractor.*/,
    /hast-*/,
    /mdast-.*/,
    /micromark.*/,
    /unist-.*/,
  ],
};
